#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

APP=$1

# Exit if nginx-cors is not enabled for this app
if [[ ! -e $DOKKU_ROOT/$APP/NGINX_CORS ]]; then
  exit 0
fi

function add_setting_location {
  sed -i -r "s/proxy_pass.*$/\0\n    $1/g" $DOKKU_ROOT/$APP/nginx.conf
}

# CORS
add_setting_location "add_header 'Access-Control-Allow-Origin' '*' always;"
add_setting_location "add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, PATCH, OPTIONS' always;"
add_setting_location "add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;"
add_setting_location "add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;"
add_setting_location "add_header 'X-Cache-Status' \$upstream_cache_status always;"

# Enable Client Side Caching
add_setting_location "add_header 'Cache-Control' 'max-age=86400' always;" # 24h
