#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/config/functions"

nginx_cors_disable() {
  declare desc="Disable CORS for a specific app"
  local cmd="nginx-cors:disable"

  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@

  verify_app_name "$2"
  local APP="$2"

  if [[ ! -e $DOKKU_ROOT/$APP/NGINX_CORS ]]; then
    dokku_log_info1 "NGINX CORS is not enabled for $APP"
  else
    dokku_log_info1 "Disabling NGINX CORS for $APP"
    rm -rf $DOKKU_ROOT/$APP/NGINX_CORS

    dokku_log_info1 "Restarting app $APP"
    dokku ps:restart "$APP"
  fi
}

nginx_cors_disable "$@"
