#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/config/functions"

nginx_cors_enable() {
  declare desc="Enable the CORS for a specific app"
  local cmd="nginx-cors:enable"

  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@

  verify_app_name "$2"
  local APP="$2"

  dokku_log_info1 "Enabling NGINX proxy CORS for $APP"
  touch $DOKKU_ROOT/$APP/NGINX_CORS

  dokku_log_info1 "Restarting app $APP"
  dokku ps:restart "$APP"
}

nginx_cors_enable "$@"
